version: "3"
services:
  selenium-hub:
    image: selenium/hub:4
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - custom_network

  chrome:
    image: selenium/node-chrome:4
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_SESSION_TIMEOUT=60
    networks:
      - custom_network

  firefox:
    image: selenium/node-firefox:4
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_SESSION_TIMEOUT=60
    networks:
      - custom_network

networks:
  custom_network:
    driver: bridge